config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :conversations
  get 'order_products/new'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get '/', to: 'users/sessions#new'
  end
  
  resources :food_businesses
  get 'food_businesses/:id/home' => 'food_businesses#home', as: 'food_business_home'
  resources :suppliers
  get 'home' => 'suppliers#home'

  resources :orders
  resources :products
  resources :order_products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/food_businesses_controller.rb
class FoodBusinessesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food_business, only: [:home, :show, :edit, :update, :destroy]

  def home
    session[:food_business_id] = @food_business.id
  end

  def index
    if current_user.user_type == 'Food Business'
      @food_businesses = FoodBusiness.where(user: current_user)
    else
      @supplier = current_user.supplier
      @my_clients = @supplier.food_businesses 
      @food_businesses = FoodBusiness.all - @my_clients
      if params[:search]
        @my_clients = @supplier.food_businesses.search(params[:search])
        @food_businesses = FoodBusiness.search(params[:search]) - @my_clients 
      end 
    end 
  end

  def show
  end

  def new
    @food_business = FoodBusiness.new
  end
  
  def edit
  end
  
  def create
    @food_business = FoodBusiness.new(food_business_params)
    @food_business.user = current_user

    respond_to do |format|
      if @food_business.save
        format.html { redirect_to @food_business, notice: 'Food business was successfully created.' }
        format.json { render :show, status: :created, location: @food_business }
      else
        format.html { render :new }
        format.json { render json: @food_business.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if params[:supplier] 
      @supplier = Supplier.find(params[:supplier])
      if @food_business.suppliers.include? @supplier
        @food_business.suppliers.delete(@supplier)
      else 
        @food_business.suppliers << @supplier        
      end
      redirect_to request.referrer
      # respond_to do |format|
      #     format.js {render inline: "window.location.reload();" }
      # end
      # redirect_to suppliers_path(food_business: @food_business) and return

    end
    respond_to do |format|
      if @food_business.update(food_business_params)
        format.html { redirect_to @food_business, notice: 'Food business was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_business }
      else
        format.html { render :edit }
        format.json { render json: @food_business.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food_business.destroy
    respond_to do |format|
      format.html { redirect_to food_businesses_url, notice: 'Food business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_food_business
      @food_business = FoodBusiness.find(params[:id])
    end

    def food_business_params
      params.require(:food_business).permit(:business_name, :address, :abn_number, :contact_number, :business_category, :email, :image)
    end
end

app/helpers/food_businesses_helper.rb
module FoodBusinessesHelper
end

app/views/food_businesses/_form.html.erb
<%= form_with(model: food_business, local: true) do |form| %>
  <% if food_business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_business.errors.count, "error") %> prohibited this food_business from being saved:</h2>

      <ul>
      <% food_business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    <%= form.text_field :business_name, placeholder: 'Business name', autofocus: true, class: 'field-input' %>

    <%= form.text_field :address, placeholder: 'Address', class: 'field-input' %>

    <%= form.text_field :contact_number, placeholder: 'Contact number', class: 'field-input' %>

    <%= form.text_field :email, placeholder: 'Email', class: 'field-input' %>
    
    <%= form.text_field :abn_number, placeholder: 'ABN', class: 'field-input' %>
  
    <%= form.select :business_category, ['Restaurant', 'Cafe\'', 'Fast Food', 'Wine Bar'], {include_blank: 'Select category'}, {class: 'field-input select' } %>

    <div class="file-box">
      <%= form.file_field :image, class: 'file' %>
    </div>

    <%= form.submit 'Create Profile', class: 'button' %>
<% end %>

app/views/food_businesses/_menu_home.html.erb
<div class="menu-box">
  <%= link_to new_order_path(food_business: @food_business) do %>
    <div class="menu-key">
      <%= fa_icon "file" %>
      <p class="key-title">New order</p>
    </div>
  <% end %>
  <%= link_to suppliers_path(food_business: @food_business) do %>
    <div class="menu-key middle-key">
      <%= fa_icon "users" %>
      <p class="key-title">My Suppliers</p>
    </div>
  <% end %>
  <%= link_to orders_path(food_business: @food_business) do %>
    <div class="menu-key">
      <%= fa_icon "archive" %>
      <p class="key-title">History</p>
    </div>
  <% end %>
  <%= link_to new_food_business_path do %>
    <div class="menu-key">
      <%= fa_icon "search" %>
      <p class="key-title">Search</p>
    </div>
  <% end %>
  <%= link_to edit_food_business_path(@food_business) do %>
    <div class="menu-key middle-key">
      <%= fa_icon "truck" %>
      <p class="key-title">Deliveries</p>
    </div>
  <% end %>
  <%= link_to food_business_path do %>
    <div class="menu-key">
      <%= fa_icon "user-circle" %>
      <p class="key-title">My profile</p>
    </div>
  <% end %>
</div>

app/views/food_businesses/_menu_index.html.erb
<% if current_user.user_type == 'Food Business' %>
  <div class="menu-box">
    <%= link_to new_food_business_path do %>
      <div class="menu-key">
        <%= fa_icon "plus" %>
        <p class="key-title">Add</p>
      </div>
    <% end %>
    <%= link_to food_businesses_path, class:'show-del-btn', remote: true do %>
      <div class="menu-key middle-key">
        <%= fa_icon "minus" %>
        <p class="key-title">Delete</p>
      </div>
    <% end %>
    <%= link_to new_food_business_path do %>
      <div class="menu-key">
        <%= fa_icon "area-chart" %>
        <p class="key-title">Stats</p>
      </div>
    <% end %>
  </div>
<% else %>
    <div class="menu-box">
    <%= link_to do %>
      <div class="menu-key">
        <%= fa_icon "area-chart" %>
        <p class="key-title">Stats</p>
      </div>
    <% end %>
    <%= link_to food_businesses_path, class:'show-del-btn', remote: true do %>
      <div class="menu-key middle-key">
        <%= fa_icon "minus" %>
        <p class="key-title">Delete</p>
      </div>
    <% end %>
    <%= link_to home_path(id: params[:supplier]) do %>
      <div class="menu-key">
        <%= fa_icon "home" %>
        <p class="key-title">Home</p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/food_businesses/_menu_show.html.erb
<% if current_user.user_type == 'Food Business'%>
  <div class="menu-box">
    <%= link_to new_food_business_path do %>
      <div class="menu-key">
        <%= fa_icon "area-chart" %>
        <p class="key-title">Stats</p>
      </div>
    <% end %>
    <%= link_to edit_food_business_path(@food_business) do %>
      <div class="menu-key middle-key">
        <%= fa_icon "pencil" %>
        <p class="key-title">Edit</p>
      </div>
    <% end %>
    <%= link_to food_business_home_path do %>
      <div class="menu-key">
        <%= fa_icon "home" %>
        <p class="key-title">Home</p>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="menu-box">
  <%= link_to do %>
    <div class="menu-key">
      <%= fa_icon "comments" %>
      <p class="key-title">Message</p>
    </div>
  <% end %>
  <%= link_to  do %>
    <div class="menu-key middle-key">
      <%= fa_icon "" %>
      <p class="key-title"></p>
    </div>
  <% end %>
  <%= link_to home_path(current_user.supplier) do %>
    <div class="menu-key">
      <%= fa_icon "home" %>
      <p class="key-title">Home</p>
    </div>
  <% end %>
</div>
<% end %>

app/views/food_businesses/_my_businesses.html.erb
<% @food_businesses.each do |food_business| %>
  <%= link_to food_business do %>
    <div class="list-item d-flex justify-content-between">
      <p><%= food_business.business_name %></p>
      <p>
        <% if current_user.user_type == 'Food Business' %>
          <%= link_to food_business_home_url(food_business), class: 'link' do %>
            <%= fa_icon "sign-in", id: 'signin' %>
          <% end %>  
        <% end %>
        <%= link_to food_business_home_url(food_business), class: 'link' do %>
          <%= fa_icon "minus-circle", class: 'text-danger hidden', id: 'delbtn' %>
        <% end %>
      </p>  
    </div>
  <% end %>
<% end %>

app/views/food_businesses/_my_clients.html.erb
<p class="list-title">My Clients</p>
<% if @my_clients && @my_clients.count > 0 %>
  <% @my_clients.each do |food_business| %>
    <%= link_to food_business_path(food_business, supplier: @supplier.id) do %>
      <div class="list-item d-flex justify-content-between">
        <p><%= food_business.business_name %></p>
        <%= form_with model: @supplier do |f| %>
          <%= link_to new_message_path(food_business: food_business, supplier: current_user.supplier), class: 'link' do %>
            <%= fa_icon "comments" %> 
          <% end %>
          <%= hidden_field_tag :food_business, food_business.id %>
          <%= f.button class: 'link form-btn text-danger' do %>
            <%= fa_icon "minus-circle" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <p class="list-item">Your list is empty</p>
<% end %>

<p class="list-title">Food Businesses</p>
<% @food_businesses.each do |food_business| %>
  <%= link_to food_business_path(food_business, supplier: @supplier.id) do %>
    <div class="list-item d-flex justify-content-between">
      <p><%= food_business.business_name %></p>
      <%= form_with model: @supplier do |f| %>
        <%= link_to food_business, class: 'link' do %>
          <%= fa_icon "phone-square" %>
        <% end %>
        <%= hidden_field_tag :food_business, food_business.id %>
        <%= f.button class: 'link form-btn' do %>
          <%= fa_icon "plus-square"%>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/food_businesses/_search.html.erb
<div class="search-bar">
  <%= form_tag(@food_business, method: "get", class: 'd-flex') do %>
    <%= hidden_field_tag :supplier, current_user.supplier.id %>
    <%= text_field_tag :search, params[:search], placeholder: "Search food business", class: 'field-input search-input' %>
    <%= submit_tag "Search", class: 'button' %>
  <% end %>
</div>

<% if params[:search] %>
  <p><strong><%= pluralize (@my_clients.count + @food_businesses.count), 'result' %> found</strong>
    <%= link_to 'Clear', food_businesses_path(supplier: @supplier), class: 'link-signin'%>
  </p>
<% end %>

app/views/food_businesses/edit.html.erb
<h2 class="text-center">Edit Profile</h2>

<%= render 'form', food_business: @food_business %>

app/views/food_businesses/home.html.erb
<p class="home-title"><%= @food_business.business_name %></p>

<% if @food_business.image %>
  <div class="profile-image">
    <%= image_tag @food_business.image_url(:thumb) %>
  </div>
<% end %>
<%# 
<div class="message-board">
  <br>
  <p class="small">Notifications</p>
</div> %>

<%= render 'menu_home' %>

app/views/food_businesses/index.html.erb
<p class='text-center'><%= current_user.company_name %></p>

<% if current_user.user_type == 'Supplier'%>
  <%= render 'search' %>
<% end %>

<br>

<% if current_user.user_type == 'Food Business'%>
  <%= render 'my_businesses' %>
<% else %>
  <%= render 'my_clients' %>
<% end %>
 
<br>

<%= render 'menu_index' %>

app/views/food_businesses/new.html.erb
<p class="text-center">New Food Business</p>

<%= render 'form', food_business: @food_business %>

app/views/food_businesses/show.html.erb
<p class="text-center heading-lg"><%= current_user.company_name %></p>

<p class="text-center heading-lg"><strong><%= @food_business.business_name %></strong></p>

<div class="info-box">
  <p><%= fa_icon "briefcase", class: 'data-title info' %> <%= @food_business.business_category %></p>
  <p><%= fa_icon "map-marker", class: 'data-title info' %> <%= @food_business.address %></p>
  <p><%= fa_icon "phone", class: 'data-title info' %> <%= @food_business.contact_number %></p>
  <p><%= fa_icon "envelope", class: 'data-title info' %> <%= @food_business.email %></p>
  <p><span class="data-title">ABN</span> <%= @food_business.abn_number %></p>
</div>

<div class="info-box">
  <p class="text-center box-title">STATS</p>
  <%# TODO: calculate weekly expenditure %>
  <p><span class="data-title">Weekly expenditure:</span> $2500</p>
  <%# TODO: calculare percentage %>
  <p><span class="data-title">Business percentage:</span> 23%</p>
</div>

<%= render 'menu_show' %>