config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :conversations
  get 'order_products/new'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get '/', to: 'users/sessions#new'
  end
  
  resources :food_businesses
  get 'food_businesses/:id/home' => 'food_businesses#home', as: 'food_business_home'
  resources :suppliers
  get 'home' => 'suppliers#home'

  resources :orders
  resources :products
  resources :order_products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :food_business
  belongs_to :supplier
  has_many :messages, -> { order(created_at: :asc) }, dependent: :destroy

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show]

  def index
    if params[:food_business]
      @conversations = Conversation.where(food_business_id: params[:food_business]).order('updated_at DESC')
    else
      @conversations = Conversation.where(supplier_id: params[:supplier]).order('updated_at DESC')
    end      
  end

  def show
    @food_business = params[:food_business]
    @supplier = params[:supplier]
    if current_user.supplier
      @receiver = @conversation.food_business.business_name
    else
      @receiver = @conversation.supplier.business_name
    end 
    @message = Message.new
  end

  private

  def set_conversation
    @conversation = Conversation.find(params[:id])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_menu.html.erb
<%# food_business menu %>
<% if params[:food_business] %>
  <div class="menu-box">
    <%= link_to suppliers_path(food_business: params[:food_business])do %>
      <div class="menu-key">
        <%= fa_icon "users" %>
        <p class="key-title">My suppliers</p>
      </div>
    <% end %>
    <%= link_to do %>
      <div class="menu-key middle-key">
        <%= fa_icon "minus" %>
        <p class="key-title">Delete</p>
      </div>
    <% end %>
    <%= link_to food_business_home_path(id: params[:food_business]) do %>
      <div class="menu-key">
        <%= fa_icon "home" %>
        <p class="key-title">Home</p>
      </div>
    <% end %>
  </div>
<%# supplier menu %>
<% else %>
  <div class="menu-box">
    <%= link_to food_businesses_path(supplier: params[:supplier])do %>
      <div class="menu-key">
        <%= fa_icon "users" %>
        <p class="key-title">My clients</p>
      </div>
    <% end %>
    <%= link_to do %>
      <div class="menu-key middle-key">
        <%= fa_icon "minus" %>
        <p class="key-title">Delete</p>
      </div>
    <% end %>
    <%= link_to home_path(id: params[:supplier]) do %>
      <div class="menu-key">
        <%= fa_icon "home" %>
        <p class="key-title">Home</p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/conversations/index.html.erb
<%# <p><%= @food_business.business_name %>
<p>My Conversations</p>
<br>
<% @conversations.each do |conversation| %>
  <%= link_to conversation_path(conversation.id, supplier: params[:supplier], food_business: params[:food_business]) do %>
    <div class="info-box conv-box">
      <p class="xs text-center">Last Message: 
        <%= conversation.messages.last.created_at.to_time.strftime('%a, %b %e, %l:%M %p') %></p>
      </p>
      <p class="conv-details"><span class="data-title">From: </span><%= conversation.supplier.business_name %></p>
      <p class="conv-details"><span class="data-title">Messages: </span><%= conversation.messages.count %></p>
      <p class="conv-details"><span class="data-title">Preview: </span><%= truncate(conversation.messages.last.content) %></p>
    </div>
  <% end %>
<% end %>

<%= render 'menu' %> 

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p>Conversation with <strong><br>
  <%= @receiver %></strong>
</p>

<% @conversation.messages.each_with_index do |message, index| %>
  <div class="<%= message.sender_id == current_user.id ? 'sender' : 'receiver' %>">
    <p><%= message.content %></p>
  </div>
  <p class="xs">
  <% if message.sender_id == current_user.id %>
    <span class="sender-details">Me</span> - 
  <% else %>
    <span class="receiver-details"><%= @receiver %> -
  <% end %> 
    <em><%= message.created_at.strftime("%m/%d/%Y, %l:%M %p") %></em>
  </p>
<% end %>

<%= render 'messages/form', message: @message %>