config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :conversations
  get 'order_products/new'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get '/', to: 'users/sessions#new'
  end
  
  resources :food_businesses
  get 'food_businesses/:id/home' => 'food_businesses#home', as: 'food_business_home'
  resources :suppliers
  get 'home' => 'suppliers#home'

  resources :orders
  resources :products
  resources :order_products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/order.rb
class Order < ApplicationRecord
  validates :supplier_id, :order_number, presence: true
  validates :order_number, uniqueness: true
  validate :valid_date? 

  belongs_to :food_business
  belongs_to :supplier
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products

  def valid_date?
    if delivery_date < 1.day.from_now(Date.today) 
      errors.add(:delivery_date, "can't be today")
    end
  end

  def net_total(order_products)
    order_products.sum(&:subtotal)
  end

  def calc_gst(order_products)
    (net_total(order_products) / 100 * 10)
  end

  def total(order_products)
    (net_total(order_products) + (net_total(order_products) / 100 * 10))
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_food_business, only: [:new, :create, :destroy]

  def index
    if params[:food_business]
      @food_business = FoodBusiness.find(params[:food_business])
      @orders = @food_business.orders if @food_business.orders
    elsif params[:supplier]
      @supplier = Supplier.find(params[:supplier])
      @orders = Order.where("supplier_id = ? AND delivery_date <= ?", @supplier, Date.today)
      @new_orders = Order.where("supplier_id = ? AND delivery_date > ?", @supplier, Date.today)
    end 
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.food_business = @food_business

    # @amount = 500
    
    # customer = Stripe::Customer.create(
    #   :email => @food_business.email,
    #   :source  => params[:stripeToken]
    # )
    # charge = Stripe::Charge.create(
    #   :customer    => customer.id, 
    #   :amount      => @amount,
    #   :description => @order.order_number,
    #   :currency    => 'aud'
    # )
  
    respond_to do |format|
      if @order.save
        format.html { redirect_to new_order_product_path(order: @order), notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { redirect_to new_order_path(food_business: @food_business) }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end

  # rescue Stripe::CardError => e
  #   flash[:error] = e.message
  #   redirect_to orders_path(food_business: @food_business)
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_path(food_business: @food_business), notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def set_food_business
      @food_business = FoodBusiness.find(params[:food_business])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:delivery_date, :supplier_id, :order_number)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def estimate(quantity, price)
    number_to_currency(quantity * price)
  end

  def find_quantity(product)
    product.order_products.find_by(order_id: @order.id).quantity
  end

end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag 'food_business', @food_business.id %>
  <%= form.text_field :order_number, placeholder: 'Order n.', class: 'field-input'  %>
  
  <p class="list-title"><%= form.label :supplier_id %></p>
  <%= form.select :supplier_id, @food_business.suppliers.map {|sup| [sup.business_name, sup.id]}, {include_blank: 'Supplier'}, class: 'field-input select' %>

  <p class="list-title"><%= form.label :delivery_date, 'Delivery' %></p>
  <p class="date-container d-flex justify-content-between">
    <%= form.date_select :delivery_date, {:order => [:day, :month, :year], start_year: Date.today.year, end_year: 1.year.since(Date.today).year }, {class: 'field-input select date'} %> 
  </p>

  <%= form.submit class: 'button' %>
<% end %>

app/views/orders/_menu_index.html.erb
<%# food_business menu %>
<% if @food_business %>
  <div class="menu-box">
    <%= link_to new_order_path(food_business: @food_business)do %>
      <div class="menu-key">
        <%= fa_icon "plus" %>
        <p class="key-title">New</p>
      </div>
    <% end %>
    <%= link_to class:'show-del-btn', remote: true do %>
      <div class="menu-key middle-key">
        <%= fa_icon "minus" %>
        <p class="key-title">Delete</p>
      </div>
    <% end %>
    <%= link_to food_business_home_url(@food_business) do %>
      <div class="menu-key">
        <%= fa_icon "home" %>
        <p class="key-title">Home</p>
      </div>
    <% end %>
  </div>
<%# supplier menu %>
<% else %>
    <div class="menu-box">
    <%= link_to food_businesses_url(@supplier) do %>
      <div class="menu-key">
        <%= fa_icon "users" %>
        <p class="key-title">My clients</p>
      </div>
    <% end %>
    <%= link_to class:'show-del-btn', remote: true do %>
      <div class="menu-key">
        <%= fa_icon "" %>
        <p class="key-title"></p>
      </div>
    <% end %>
    <%= link_to home_url(@supplier) do %>
      <div class="menu-key">
        <%= fa_icon "home" %>
        <p class="key-title">Home</p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/orders/_menu_show.html.erb
<% if @food_business %>
  <div class="menu-box">
    <%= link_to new_order_path(food_business: @order.food_business)do %>
      <div class="menu-key">
        <%= fa_icon "plus" %>
        <p class="key-title">New</p>
      </div>
    <% end %>
    <%= link_to orders_path(food_business: @order.food_business) do %>
      <div class="menu-key middle-key">
        <%= fa_icon "archive" %>
        <p class="key-title">History</p>
      </div>
    <% end %>
    <%= link_to food_business_home_path(id: @order.food_business) do %>
      <div class="menu-key">
        <%= fa_icon "home" %>
        <p class="key-title">Home</p>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="menu-box">
    <%= link_to do %>
      <div class="menu-key">
        <%= fa_icon "print" %>
        <p class="key-title">Print</p>
      </div>
    <% end %>
    <%= link_to orders_path(supplier: @order.supplier) do %>
      <div class="menu-key middle-key">
        <%= fa_icon "archive" %>
        <p class="key-title">History</p>
      </div>
    <% end %>
    <%= link_to home_path(id: @order.supplier) do %>
      <div class="menu-key">
        <%= fa_icon "home" %>
        <p class="key-title">Home</p> 
      </div>
    <% end %>
  </div>
<% end %>

app/views/orders/_new_orders.html.erb
<p class='list-title'>New Orders</p>
<% @new_orders.each do |order| %>
  <%= link_to order_path(order, supplier_id: @supplier.id) do %>
    <div class="info-box-orders d-flex justify-content-between">
      <p><span class="order-title">Order n.: </span><%= order.order_number %></p>
      <% if current_user.supplier %>
        <p><span class="order-title">From: </span><%= order.food_business.business_name %></p>
      <% else %>
        <p><span class="order-title">To: </span><%= order.supplier.business_name %></p>
      <% end %>
      <p><span class="order-title">Delivery Date: </span><%= order.delivery_date %></p>
      <p><span class="order-title">Total: </span><%= number_to_currency(order.gross_total) %></p>
      <p>
        <%= link_to class: 'link' do %>
          <%= fa_icon "print" %>
        <% end %>  
        <%= link_to class: 'link' do %>
          <%= fa_icon "archive" %>
        <% end %>
      </p>  
    </div>
  <% end %>
<% end %>

app/views/orders/_orders.html.erb
<p class='list-title'>Orders history</p>
<% @orders.each do |order| %>
  <%= link_to order do %>
    <div class="info-box-orders d-flex justify-content-between">
      <p><span class="order-title">Order n.: </span><%= order.order_number %></p>
      <% if current_user.supplier %>
        <p><span class="order-title">From: </span><%= order.food_business.business_name %></p>
      <% else %>
        <p><span class="order-title">To: </span><%= order.supplier.business_name %></p>
      <% end %>
      <p><span class="order-title">Delivery Date: </span><%= order.delivery_date %></p>
      <p><span class="order-title">Total: </span><%= number_to_currency(order.gross_total) %></p>
      <p>
        <%= link_to class: 'link' do %>
          <%= fa_icon "print", id: 'signin' %>
        <% end %>
        <% if @food_business %>  
          <%= link_to order_path(id: order.id, food_business: @food_business.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'link' do %>
            <%= fa_icon "minus-circle", class: 'text-danger', id: 'delbtn' %>
          <% end %>
        <% else %>
          <%= link_to order_path(order, supplier_id: @supplier.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'link' do %>
            <%= fa_icon "minus-circle", class: 'text-danger hidden', id: 'delbtn' %>
          <% end %>
        <% end %>        
      </p>  
    </div>
  <% end %>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p class='text-center'>
  <%= @food_business ? @food_business.business_name : @supplier.business_name %> 
</p>

<%# new orders %>
<%= render 'new_orders' if @supplier %>

<br>

<%# Order history %>
<%= render 'orders'%>

<br>

<div class="info-box-orders">
  <p class="text-center box-title">Data</p>
  <%# TODO: calculate weekly expenditure %>
  <p><span class="data-title">Weekly total:</span> $1400</p>
  <%# TODO: calculare percentage %>
  <p><span class="data-title">Last week:</span> $1300</p>
  <p><span class="data-title">Budget:</span> $1350</p>
</div>


<br>

<%= render 'menu_index' %>

app/views/orders/new.html.erb
<p><%= @food_business.business_name %></p>

<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<p class='text-center'>
  <% if current_user.supplier %>
    <%= @order.supplier.business_name %>
  <% else %>
    <%= @order.food_business.business_name %>
  <% end %>
</p>

<p class="box-title">Order <%= @order.order_number %> - <%= @order.created_at.strftime("%m/%d/%Y") %></p>
<hr>

<div class="small d-flex justify-content-around">
  <% if current_user.supplier %>
    <p>From: <%= @order.food_business.business_name %></p>
  <% else %>
    <p>To: <%= @order.supplier.business_name %></p>
  <% end %>
  <p>Delivery: <%= @order.delivery_date.strftime("%m/%d/%Y") %></p>
</div>

<div class="info-box info-box-order">
  <% @order.products.each do |product| %>
    <div class="row order-row xs">
      <div class="order-product">
        <%= product.name %>
        <% if product.product_variety %>
          <span> - <%= product.product_variety %></span>
        <% end %>
      </div>
      <div class="order-quantifier">
        <%= find_quantity(product) %><%= product.quantifier %>
      </div>
      <div class="order-price">
        <%= estimate(find_quantity(product), product.price) %>
      </div>
    </div>
  <% end %>

  <div class="total xs">
    <p class="text-right"><span class="tot-title">GST: </span><%= number_to_currency(@order.gross_total) %><p>
    <p class="text-right"><span class="tot-title">Total: </span><%= number_to_currency(@order.gst) %></p>
  </div>
</div>

<% if current_user.user_type == 'Food Business'%>
  <%= form_tag order_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Amount: <%= number_to_currency(@order.gross_total) %></span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount="<%= @amount %>"
            data-locale="auto"></script>
  <% end %>
<% end %>

<%= render 'menu_show' %>