config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :conversations
  get 'order_products/new'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get '/', to: 'users/sessions#new'
  end
  
  resources :food_businesses
  get 'food_businesses/:id/home' => 'food_businesses#home', as: 'food_business_home'
  resources :suppliers
  get 'home' => 'suppliers#home'

  resources :orders
  resources :products
  resources :order_products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/supplier.rb
class Supplier < ApplicationRecord
  include ImageUploader::Attachment.new(:image)

  validates :business_name, :address, :abn_number, :contact_number, :supplier_type, :email, presence: true
  validates :business_name, :abn_number, uniqueness: true

  belongs_to :user
  has_and_belongs_to_many :food_businesses
  has_many :orders, through: :food_businesses
  has_many :products, dependent: :destroy

  def self.search(search)
    keyword = search.downcase
    where("lower(business_name) LIKE ? OR lower(supplier_type) LIKE ?", "%#{keyword}%", "%#{keyword}%")
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  def home
  end

  def index
    @food_business = FoodBusiness.find(params[:food_business])

    if params[:search]
      @my_suppliers = @food_business.suppliers.search(params[:search])
      @suppliers = Supplier.search(params[:search]) - @my_suppliers
    else
      @my_suppliers = @food_business.suppliers
      @suppliers = Supplier.all - @my_suppliers
    end
  end

  def show
  end

  def new
    @supplier = Supplier.new
  end

  def edit
  end

  def create
    @supplier = Supplier.new(supplier_params)
    @supplier.user = current_user
    @supplier.business_name = current_user.company_name

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if params[:food_business] 
      @food_business = FoodBusiness.find(params[:food_business])
      if @supplier.food_businesses.include? @food_business
        @supplier.food_businesses.delete(@food_business)
      else 
        @supplier.food_businesses << @food_business        
      end
      redirect_to request.referrer
      
      # respond_to do |format|
      #     format.js 
      # end
      # redirect_to food_businesss_path(food_business: @food_business) and return

    end
    respond_to do |format|
      if @supplier.update(supplier_params)
       
        format.html { redirect_to home_path, notice: 'Supplier was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: 'Supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      if current_user.user_type == 'Supplier'
        @supplier = current_user.supplier
      else
        @supplier = Supplier.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:business_name, :address, :abn_number, :contact_number, :supplier_type, :email, :image)
    end

end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier, local: true) do |form| %>
  <% if supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% supplier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :business_name, placeholder: current_user.company_name, class: 'field-input' %>

  <%= form.text_field :address, placeholder: 'Address', autofocus: true, class: 'field-input' %>

  <%= form.text_field :contact_number, placeholder: 'Contact number', class: 'field-input' %>

  <%= form.text_field :email, placeholder: 'Business Email', class: 'field-input' %>

  <%= form.text_field :abn_number, placeholder: 'ABN', class: 'field-input' %>

  <%= form.select :supplier_type, ['Vegetables', 'Meat', 'Fish', 'Dry Goods', 'Dairy', 'Drinks', 'Baked Goods/Pastry'], {include_blank: 'Select category'}, {class: 'field-input select' } %>

  <div class="file-box">
    <%= form.file_field :image, class: 'file' %>
  </div>
  
  <%= form.submit 'Create Profile', class: 'button' %>
<% end %>

app/views/suppliers/_menu_home.html.erb
<div class="menu-box">
  <%= link_to orders_path(supplier: current_user.supplier) do %>
    <div class="menu-key">
      <%= fa_icon "file" %>
      <p class="key-title">Orders</p>
    </div>
  <% end %>
  <%= link_to food_businesses_path(supplier: current_user.supplier) do %>
    <div class="menu-key middle-key">
      <%= fa_icon "users" %>
      <p class="key-title">My clients</p>
    </div>
  <% end %>
  <%= link_to conversations_path(supplier: current_user.supplier) do %>
    <div class="menu-key">
      <%= fa_icon "comments" %>
      <p class="key-title">Messages</p>
    </div>
  <% end %>
    <%= link_to products_path(supplier: current_user.supplier) do %>
    <div class="menu-key">
      <%= fa_icon "th-list" %>
      <p class="key-title">My products</p>
    </div>
  <% end %>
  <%= link_to do %>
    <div class="menu-key middle-key">
      <%= fa_icon "truck" %>
      <p class="key-title">Deliveries</p>
    </div>
  <% end %>
  <%= link_to supplier_path(current_user.supplier) do %>
    <div class="menu-key">
      <%= fa_icon "user-circle" %>
      <p class="key-title">My profile</p>
    </div>
  <% end %>
</div>

app/views/suppliers/_menu_index.html.erb
<div class="menu-box">
  <%= link_to new_order_path(food_business: @food_business) do %>
    <div class="menu-key">
      <%= fa_icon "file" %>
      <p class="key-title">Order</p>
    </div>
  <% end %>
  <%= link_to new_food_business_path do %>
    <div class="menu-key">
      <%= fa_icon "minus" %>
      <p class="key-title">Delete</p>
    </div>
  <% end %>
  <%= link_to food_business_home_url(@food_business) do %>
    <div class="menu-key">
      <%= fa_icon "home" %>
      <p class="key-title">Home</p>
    </div>
  <% end %>
</div>

app/views/suppliers/_menu_show.html.erb
<% if current_user.user_type == 'Food Business' %>
  <div class="menu-box">
    <%= link_to suppliers_path(food_business: params[:food_business]) do %>
      <div class="menu-key">
        <%= fa_icon "users" %>
        <p class="key-title">My Suppliers</p>
      </div>
    <% end %>
    <%= link_to do %>
      <div class="menu-key middle-key">
        <%= fa_icon "" %>
        <p class="key-title"></p>
      </div>
    <% end %>
    <%= link_to food_business_home_path(id: params[:food_business]) do %>
      <div class="menu-key">
        <%= fa_icon "home" %>
        <p class="key-title">Home</p>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="menu-box">
    <%= link_to do %>
      <div class="menu-key">
        <%= fa_icon "area-chart" %>
        <p class="key-title">Stats</p>
      </div>
    <% end %>
    <%= link_to edit_supplier_path(@supplier) do %>
      <div class="menu-key middle-key">
        <%= fa_icon "pencil" %>
        <p class="key-title">Edit</p>
      </div>
    <% end %>
    <%= link_to home_path do %>
      <div class="menu-key">
        <%= fa_icon "home" %>
        <p class="key-title">Home</p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/suppliers/_search.html.erb
<div class="search-bar">
  <%= form_tag(@supplier, method: "get", class: 'd-flex') do %>
    <%= hidden_field_tag :food_business, @food_business.id %>
    <%= text_field_tag :search, params[:search], placeholder: "Search supplier", class: 'field-input search-input' %>
    <%#= select_tag (:supplier_type, ['Vegetables', 'Meat', 'Fish', 'Dry Goods', 'Dairy', 'Drinks', 'Baked Goods/Pastry'], {prompt: 'Select category'}, {class: 'field-input select' }) %>
    <%= submit_tag "Search", class: 'button' %>
  <% end %>
</div>

<% if params[:search] %>
  <p><strong><%= pluralize (@my_suppliers.count + @suppliers.count), 'result' %> found</strong>
    <%= link_to 'Clear', suppliers_path(food_business: @food_business), class: 'link-signin'%>
  </p>
<% end %>

app/views/suppliers/_suppliers.html.erb
<p class="list-title">My Suppliers</p>
<% if @food_business && @food_business.suppliers.count > 0 %>
  <% @my_suppliers.each do |supplier| %>
    <%= link_to supplier_path(supplier, food_business: @food_business) do %>
      <div class="list-item d-flex justify-content-between">
        <p><%= supplier.business_name %></p>
        <%= form_with model: @food_business do |f| %>
          <%= link_to new_message_path(food_business: @food_business, supplier: supplier), class: 'link' do %>
            <%= fa_icon "comments" %> 
          <% end %>
          <%= hidden_field_tag :supplier, supplier.id %>
          <%= f.button class: 'link form-btn' do %>
            <%= fa_icon "minus-circle", class: 'link text-danger' %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <p class="list-item">Your list is empty</p>
<% end %>

<p class="list-title">Suppliers</p>
<% @suppliers.each do |supplier| %>
  <%= link_to supplier_path(supplier, food_business: @food_business) do %>
    <div class="list-item d-flex justify-content-between">
      <p><%= supplier.business_name %></p>
      <%= form_with model: @food_business, remote: true do |f| %>
        <%= link_to supplier, class: 'link' do %>
          <%= fa_icon "phone-square" %>
        <% end %>
        <%= hidden_field_tag :supplier, supplier.id %>
        <%= f.button class: 'link form-btn' do %>
          <%= fa_icon "plus-square"%>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/suppliers/edit.html.erb
<h2 class="text-center">Edit Profile</h2>

<%= render 'form', supplier: @supplier %>

app/views/suppliers/home.html.erb
<p class="home-title"><%= current_user.company_name %></p>

<% if current_user.supplier.image %>
  <div class="profile-image">
    <%= image_tag current_user.supplier.image_url(:thumb) %>
  </div>
<% end %>

<%# <div class="message-board"></div> %>

<%= render 'menu_home' %>

app/views/suppliers/index.html.erb
<p class="home-title"><%= @food_business.business_name %></p>

<%= render 'search' %>

<div id="list-container">
  <%= render 'suppliers' %>
</div>

<%= render 'menu_index'%>

app/views/suppliers/new.html.erb
<hp class="text-center">Create profile</hp>

<%= render 'form', supplier: @supplier %>

app/views/suppliers/show.html.erb
<p class="text-center heading-lg"><%= current_user.company_name %></p>

<div class="info-box">
  <p><%= fa_icon "briefcase", class: 'data-title info' %> <%= @supplier.supplier_type %></p>
  <p><%= fa_icon "map-marker", class: 'data-title info' %> <%= @supplier.address %></p>
  <p><%= fa_icon "phone", class: 'data-title info' %> <%= @supplier.contact_number %></p>
  <p><%= fa_icon "envelope", class: 'data-title info' %> <%= @supplier.email %></p>
  <p><span class="data-title">ABN</span> <%= @supplier.abn_number %></p>
</div>

<div class="info-box">
  <p class="text-center box-title">STATS</p>
  <%# TODO: calculate weekly expenditure %>
  <p><span class="data-title">Market share:</span> 19%</p>
  <%# TODO: calculare percentage %>
  <p><span class="data-title">Member since:</span> 10/01/2011</p>
</div>

<%= render 'menu_show' %>